name: Deplou Website

on:
  push: 
    branches: 
      - main

jobs: 
  validate-html: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5-validator-action@v1
        with:
          file: index.html

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Configurar Github pages
        uses: actions/configure-pages@v3

      - name: Publicar Github pages
        uses: actions/upload-pages-artifact@v2